export const MODULE_META = {
  foundations: {
    title: "Foundations",
    subtitle: "Your Agent's Building Blocks",
    description: "Skills are the domain expertise layer of your SE agent — what it knows, when to apply it, and how it works.",
    color: "var(--color-mod-foundations)",
    colorClass: "text-electric-500",
    bgClass: "bg-electric-500",
    icon: "puzzle",
    slug: "foundations",
    order: 1,
  },
  "building-skills": {
    title: "Building Skills",
    subtitle: "Giving Your Agent SE Expertise",
    description: "Build the skills that turn Claude Code into a specialized SE agent — discovery, demo prep, RFP response, and follow-up.",
    color: "var(--color-mod-building)",
    colorClass: "text-mod-building",
    bgClass: "bg-mod-building",
    icon: "wrench",
    slug: "building-skills",
    order: 2,
  },
  orchestration: {
    title: "Orchestration",
    subtitle: "Making Your Agent Autonomous",
    description: "Chain skills into multi-step workflows so your agent acts on its own — routing, handoffs, and state management.",
    color: "var(--color-mod-orchestration)",
    colorClass: "text-amber-500",
    bgClass: "bg-amber-500",
    icon: "flow",
    slug: "orchestration",
    order: 3,
  },
  "intent-engineering": {
    title: "Intent Engineering",
    subtitle: "Deploying Your SE Agent",
    description: "Design the full system — goals, constraints, memory, and evaluation — that makes your SE agent accountable and production-ready.",
    color: "var(--color-mod-intent)",
    colorClass: "text-mod-intent",
    bgClass: "bg-mod-intent",
    icon: "compass",
    slug: "intent-engineering",
    order: 4,
  },
  "building-your-agent": {
    title: "Building Your SE Agent",
    subtitle: "From Skills to a Working Agent",
    description: "Put it all together — design your skill library, connect to real tools via MCP, build account context systems, and deploy a production SE agent.",
    color: "var(--color-mod-practice)",
    colorClass: "text-mod-practice",
    bgClass: "bg-mod-practice",
    icon: "rocket",
    slug: "building-your-agent",
    order: 5,
  },
} as const;

export type ModuleSlug = keyof typeof MODULE_META;
